### ISSUE TITLE
Refresh Token object

### ISSUE THREAD

**Issue by pierceinc** [laravel-notification-channels/apn#98] opened 2020-05-10 20:04 UTC
Since I'm using a worker to send the notification.
the token eventually expires. Should there be a way to refresh it?
Per apple doc, you have to refresh Token every 20-60 mins

**Comment by dwightwatson** [comment] 2020-05-10 22:33
Where did you see that in the Apple docs?

**Comment by pierceinc** [comment] 2020-05-10 22:41
Currently, I have to restart the worker to get a new token.
It will work initially with a 200 response but a while later I'll get 403 response with "Provider Token Expire" message

Here:
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns

At the end of the doc 

> Refresh Your Token Regularly
For security, APNs requires you to refresh your token regularly. Refresh your token no more than once every 20 minutes and no less than once every 60 minutes. APNs rejects any request whose token contains a timestamp that is more than one hour old. Similarly, APNs reports an error if you recreate your tokens more than once every 20 minutes.
On your provider server, set up a recurring task to recreate your token with a current timestamp. Encrypt the token again and attach it to subsequent notification requests.

**Comment by dwightwatson** [comment] 2020-05-10 22:44
Wow... I wonder if this is a recent change. I haven’t changed my tokens in a long time - and I was under the impression they still worked. 

This could turn out to be quite a tricky problem to solve.

**Comment by pierceinc** [comment] 2020-05-10 22:51
I'm new to this and assume apple change things all the time. Maybe older accounts/keys are under different rules. I don't understand enough Laravel to reset the Token or Client instant for the worker. Was it set initially by the service provider? Can't seems to replace it with re-registering the service provider or bind another instace of Token and Client? another method that I have't tried is you seems to get a client from message instance if available may be I can make a different instance of client that way?

**Comment by dwightwatson** [comment] 2020-05-10 23:09
Having a quick read of this now and I think we're actually okay. You don't provide a token to this package - you provide the key ID, team ID and certificate. I would assume that under the hood (the pushok library) is generating the JWT token using these credentials.

I've had workers running for about 3 months with this latest version running and never seen this issue crop up so I'm curious what the deal is.

**Comment by pierceinc** [comment] 2020-05-10 23:19
Yep and I provided all of that and tested and work on local and remote. The next day it stops working and I have to create a listener to see what's up with the response to see the 403 error.
And whenever I restarted the worker it starts to work again. when I debug the Pushok token remains the same throughout.

**Comment by pierceinc** [comment] 2020-05-11 17:50
So I ended up creating a singleton class called to ClientManager that contains Pushok Token and Client inject into ApnMessage using the "via" method and have a job that runs every 30 mins to refresh the token. And seems to be working fine now. 

Not sure if it's the best way because I don't how the original client got injected in the ApnChannel class constructor.

**Comment by dwightwatson** [comment] 2020-05-11 23:10
I'm really not sure what to do here because I can't replicate the issue. I wonder if it's worth opening an issue on the pushok library because that's where the actual token generation is handled - this package just wraps it up into a notification channel.

**Comment by grEvenX** [comment] 2020-06-05 12:31
@dwightwatson Related? https://github.com/edamov/pushok/issues/92

**Comment by grEvenX** [comment] 2020-06-05 13:37
@dwightwatson I can confirm this is an issue in this library. The PushOK library pushes the responsibility of managing the tokens to the implementor.

I think this should be either managed by this library, or made adjustments that makes it easy for the Laravel application to manage the tokens used due to the complexity involved.
From Apple's documentation:
> Refresh Your Token Regularly
For security, APNs requires you to refresh your token regularly. Refresh your token no more than once every 20 minutes and no less than once every 60 minutes. APNs rejects any request whose token contains a timestamp that is more than one hour old. Similarly, APNs reports an error if you recreate your tokens more than once every 20 minutes.
On your provider server, set up a recurring task to recreate your token with a current timestamp. Encrypt the token again and attach it to subsequent notification requests.

So we need some way to reuse the same Token for 20-60 minutes, before it needs to be rotated with a new one.

**Comment by pierceinc** [comment] 2020-06-06 06:30
I concur.  I'm just not experienced enough to pull that Client/Token and replace it with a new instance. Luckily I can create a singleton of the client/token that I can manage to refresh every 30 mins and use that to inject when creating a message. Don't know if it's a bad practice/security concern

**Comment by dwightwatson** [comment] 2020-06-06 06:59
Cool, thanks everyone for the additional information here.

Turns out I have an unrelated issue with push notifications on my end that I need resolved by our app developers, and then I can make some time to work out what's going on here.

It's unfortunate that it's not handled by Pushok - doesn't sound like they've ruled it out though. If everyone who uses Pushok is going to need to cycle tokens it feels like a better place for rather than everyone having to roll their own system. 

If anyone has time to have a crack at this either upstream of for this package that would be fantastic, I'm happy to look over any PRs for for this package.

**Comment by dwightwatson** [comment] 2020-06-10 05:51
Just having a little review here - [looking at the service provider](https://github.com/laravel-notification-channels/apn/blob/master/src/ApnServiceProvider.php#L19-L27).

Every time Laravel creates an instance of the `ApnChannel` it's going to use these bindings. They're not singletons - so they should be newed up from scratch every single time. 

So without actually testing this - I'd expect `Token::create()` to be called every time the channel is used, so tokens should always be current?

Am I missing something here? Looking at [this comment](https://github.com/edamov/pushok/issues/92#issuecomment-591852570) it sounds like the issue is that we'd be generating the token too frequently (if you're sending more than one notification per 20 minute block:
>Refresh your token no more than once every 20 minutes and no less than once every 60 minutes.

**Comment by dwightwatson** [comment] 2020-06-10 05:52
Because, if it was just a matter of generating too many tokens we could probably get away with chucking that token into a 20 minute cache:

```php
$this->app->bind(Token::class, function ($app) {
    return Cache::remember(Token::class, now()->addMinutes(20), function ($app) {
        $options = Arr::except($app['config']['broadcasting.connections.apn'], 'production');

        return Token::create($options);
    });
});
```

**Comment by grEvenX** [comment] 2020-06-10 06:57
@dwightwatson That's what I thought too, but I have confirmed through Xdebug and break-points that the problem is that these are injected only ONCE. The reason is as explained earlier, that there is only one ApnChannel instance created which is kept in the application context. The Client (and thus the token) is injected once in this instance and remain in memory. The binding isn't a singleton, but as long as the instance is only injected once it's in-effect a singleton :)

**Comment by grEvenX** [comment] 2020-06-10 07:03
@dwightwatson I think this could be resolved with the approach you mentioned if the ApnChannel is refactored a bit to either not take the `Client` as part of the constructor, or injecting it each time it's being used in the public `send()` method.

**Comment by dwightwatson** [comment] 2020-06-10 07:04
Ah yes - I see what you mean. Looks like [the base `Manager` class is holding on to the channel instance after it's created](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Manager.php#L86-L91).

**Comment by dwightwatson** [comment] 2020-06-10 07:05
Yeah, so we'd need to new-up an instance of Pushok every time it's called. It just feels so hacky though.

Reckon we could get away with just creating a new token every time the channel is used, instead of having to worry about any time constraints? Or do we really need to adhere to those constraints?

**Comment by grEvenX** [comment] 2020-06-10 07:24
@dwightwatson Unfortunately, I think not adhering to the constraints can quickly run into a situation where you are rate-limited and notifications are not delivered. E.g. in our company we  send many thousand notifications during a short period of time from workers.

I think maybe the most optimal solution would be to cache the Client instance rather than the Token itself, since unfortunately PushOk doesn't allow you to update a Client's token as far as I can see. That way you are also able to keep a connection open, which is recommended by Apple and can be seen in the PushOk documentation:
> setAutoCloseConnections(): Set if the client should automatically close the connections or not. Apple recommends keeping connections open if you send more than a few notification per minutes.

**Comment by grEvenX** [comment] 2020-06-10 07:29
@dwightwatson If it feels to "hacky" to involve Cache in the library code here, I guess if the library just resolved the Client instance each time it sends, the snippet you shared could be added to the docs to explain how to cache either the Client or Token to meet Apple's demands.
The question is maybe if this isn't the behaviour all users of the library would want "by default" anyway :)

**Comment by dwightwatson** [comment] 2020-06-10 07:45
Cool - so it's worth noting you can currently pass a client instance in using the `via()` method on a message instance, which is a nice workaround.

I think the hacky part is calling the container from inside the `ApnChannel`, explicitly skipping normal dependency injection. Also, using the cache in the binding also feels wrong.

Maybe the answer here instead is the `ApnMessage` taking in a client through `via`, otherwise falling back to getting an instance the client itself. And wrapping that in a cache, so it doesn't do it more than once every 20 minutes. Does that make sense (I don't know if I described it clearly enough)?

**Comment by grEvenX** [comment] 2020-06-10 07:47
@dwightwatson Sounds like a good approach to me 👍

**Comment by dwightwatson** [comment] 2020-06-10 09:37
Alright - I've just opened a PR that lays out the approach I think that will do the trick. Going to go through and get the tests up to speed and give it a trial run too. Would love feedback from anyone looking at this issue.

**Comment by dwightwatson** [comment] 2020-06-10 10:20
Alright, I think we've got this under control now. Thanks everyone for their input.

Tagged v2.3.0.

**Comment by grEvenX** [comment] 2020-06-10 10:20
@dwightwatson Fast and clean code  👏. Do you want to make a release with it, or do you want someone to test it out in a development environment first from the master branch ?

**Closed by dwightwatson** 2020-06-10 10:20 UTC

**Comment by dwightwatson** [comment] 2020-06-10 10:22
I've tested it locally and verified that it works as expected, going to roll it into to production now for more testing but I don't anticipate problems. Of course, if you find any, let me know!

**Comment by grEvenX** [comment] 2020-06-10 10:22
@dwightwatson Thanks for the speedy fix 👏   Will upgrade and test in our development environment before we roll it out in production :)
